//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootCamp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BootCamp.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is already verified..
        /// </summary>
        public static string AccountAlreadyVerifiedError {
            get {
                return ResourceManager.GetString("AccountAlreadyVerifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account created..
        /// </summary>
        public static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account verified..
        /// </summary>
        public static string AccountVerified {
            get {
                return ResourceManager.GetString("AccountVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Verification Pending..
        /// </summary>
        public static string AccountVerifyError {
            get {
                return ResourceManager.GetString("AccountVerifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biceps are required..
        /// </summary>
        public static string BicepsError {
            get {
                return ResourceManager.GetString("BicepsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootcamp Description cannot be greater than 250.
        /// </summary>
        public static string BootCampAboutLengthError {
            get {
                return ResourceManager.GetString("BootCampAboutLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BootCamp Created Successfully..
        /// </summary>
        public static string BootCampCreated {
            get {
                return ResourceManager.GetString("BootCampCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created another bootcamp falling in these dates..
        /// </summary>
        public static string BootcampError1 {
            get {
                return ResourceManager.GetString("BootcampError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootcamp name cannot be greater than 100.
        /// </summary>
        public static string BootCampNameLengthError {
            get {
                return ResourceManager.GetString("BootCampNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootcamp can only be started on Sunday..
        /// </summary>
        public static string BootCampStartDayError {
            get {
                return ResourceManager.GetString("BootCampStartDayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest is required..
        /// </summary>
        public static string ChestError {
            get {
                return ResourceManager.GetString("ChestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address already exists..
        /// </summary>
        public static string EmailExistsError {
            get {
                return ResourceManager.GetString("EmailExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address..
        /// </summary>
        public static string EmailInvalidError {
            get {
                return ResourceManager.GetString("EmailInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailMandatoryError {
            get {
                return ResourceManager.GetString("EmailMandatoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found..
        /// </summary>
        public static string EmailNotExistError {
            get {
                return ResourceManager.GetString("EmailNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send email..
        /// </summary>
        public static string EmailSendingError {
            get {
                return ResourceManager.GetString("EmailSendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occured on server. We are working to resolve the issue..
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight is required..
        /// </summary>
        public static string GoalWeightError {
            get {
                return ResourceManager.GetString("GoalWeightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height is required..
        /// </summary>
        public static string HeightError {
            get {
                return ResourceManager.GetString("HeightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hips are required..
        /// </summary>
        public static string HipsError {
            get {
                return ResourceManager.GetString("HipsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length exceeds 500 character limit..
        /// </summary>
        public static string LengthError500 {
            get {
                return ResourceManager.GetString("LengthError500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email or Password..
        /// </summary>
        public static string LoginCredentialsError {
            get {
                return ResourceManager.GetString("LoginCredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in..
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements are required.
        /// </summary>
        public static string MeasurementError {
            get {
                return ResourceManager.GetString("MeasurementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password needs to be between 6 to 20 characters in length..
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequiredError {
            get {
                return ResourceManager.GetString("PasswordRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone No..
        /// </summary>
        public static string PhoneNoError {
            get {
                return ResourceManager.GetString("PhoneNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thighs are required..
        /// </summary>
        public static string ThighsError {
            get {
                return ResourceManager.GetString("ThighsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpperArm is required..
        /// </summary>
        public static string UpperArmError {
            get {
                return ResourceManager.GetString("UpperArmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist is required..
        /// </summary>
        public static string WaistError {
            get {
                return ResourceManager.GetString("WaistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is required..
        /// </summary>
        public static string WeightError {
            get {
                return ResourceManager.GetString("WeightError", resourceCulture);
            }
        }
    }
}
